# DataLoader parameters
train_src_file: "datasets/bpe_data/train.BPE.10000.en"
train_tgt_file: "datasets/bpe_data/train.BPE.10000.vi"

dev_src_file: "datasets/bpe_data/dev.BPE.10000.en"
dev_tgt_file: "datasets/bpe_data/dev.BPE.10000.vi"

test_src_file: "datasets/bpe_data/test.BPE.10000.en"
test_tgt_file: "datasets/bpe_data/test.BPE.10000.vi"

vocab_file: "datasets/bpe_data/vocab.bpe.10000"

# Embeder parameters
pretrain_vectors: null
embedd_size: 300

# Encoder-Decoder parameters
num_enc_layers: 8
num_dec_layers: 8
hidden_size: 300
dropout: 0.2
init_weight: 0.1

# Trainer parameters
device: 'cuda'
batch_size: 16
epochs: 1000
learning_rate: 0.001
early_stop: 20 # Set value = '0' when not use early stopping and value > 0 when stop training with this value epoch loss not decrease