# DataLoader parameters
corpus: null

# Embeder parameters
pretrain_vectors: null
embedd_size: 300

# Encoder-Decoder parameters
num_enc_layers: 8
num_dec_layers: 8
hidden_size: 300
dropout: 0.2
init_weight: 0.1

# Trainer parameters