# DataLoader parameters
test_src_file: "datasets/feat_data/test.en"
test_tgt_file: "datasets/raw_data/test.vi"

chkpt_file: "outputs/nmt_model_chkpt.pt"

# Embeder parameters
pretrain_vectors: null
embedd_size: 300
feats: [["deprel", 10]]

# Encoder-Decoder parameters
num_enc_layers: 8
num_dec_layers: 8
hidden_size: 300
dropout: 0.2
init_weight: 0.1

# Translate paremeters
device: 'cuda'
batch_size: 16
beam_size: 4
max_length: 256