# DataLoader parameters
train_src_file: "datasets/feat_data/train.en"
train_tgt_file: "datasets/feat_data/train.vi"

dev_src_file: "datasets/feat_data/dev.en"
dev_tgt_file: "datasets/feat_data/dev.vi"

test_src_file: "datasets/feat_data/test.en"
test_tgt_file: "datasets/feat_data/test.vi"

vocab_file: "datasets/bpe_data/vocab.bpe.10000"

feats: [] #[["deprel", 10]]
# Embeder parameters
pretrain_vectors: null
embedd_size: 300

# Encoder-Decoder parameters
num_enc_layers: 8
num_dec_layers: 8
hidden_size: 300
dropout: 0.2
init_weight: 0.1

# Trainer parameters
device: 'cuda'
batch_size: 16
train_steps: 200000
eval_steps: 10000
save_checkpoint_steps: 5000
learning_rate: 0.001
early_stop: 20 # Set value = '0' when not use early stopping and value > 0 when stop training with this value epoch loss not decrease